### ISSUE TITLE
При подключении через Gradio.live финальные изображения не выводятся

### ISSUE THREAD

**Issue by EisenCrab** [serpotapov/stable-diffusion-portable#10]
Доброго времени суток.
Проблема следующая: При подключении через Gradio.live финальные изображения не выводятся. Стриминг превью работает корректно, как и все остальные функции, однако по завершении генерации изображение просто отсутствует, так, будто страница загружена с нуля.
Процесс генерации:
![image](https://user-images.githubusercontent.com/117412637/221681568-dd535ecc-5bea-42d5-8254-c5feaf96b287.png)
Результат по завершении генерации:
![image](https://user-images.githubusercontent.com/117412637/221681751-6070b2df-ba75-4163-8045-64c6d2889b95.png)
Если после генерации тыкнуть в поле для изображений, то ниже появляется надпись "Loading" и остаётся там до обновления страницы или перезагрузки UI.
Пробовал заходить с разных устройств и разных браузеров. Пробовал менять формат итогового изображения. Всегда один результат. 
К сожалению, не смог найти решение проблемы, потому прошу помощи здесь.

**Comment by serpotapov** [comment]
Приветствую 🖐
Проверьте настройки предпросмотра генереации.
Settings ➜ Live previews

**Comment by EisenCrab** [comment]
Большое спасибо! Проблема решилась переключением в Live previews параметра "Image creation progress preview mode" с "Approx NN" на "Full".
