### ISSUE TITLE
Оптимизация папки питона

### ISSUE THREAD

**Issue by Lex-DRL** [serpotapov/stable-diffusion-portable#11]
В данный момент в репо лежит питон, установленный в самой дефолтной конфигурации. Можно в несколько раз сократить вес архива за счёт того, что:
- для данного сетапа питона - не нужны ни доки, ни test suite, ни tcl/tk. Питон в webui используется только как лончер, для создания venv.
- все `*.pyc`-кэши - если надо, создадутся на машине юзера
- вместо винрара можно использовать 7zip в режиме сжатия ultra
- до кучи - я бы ещё сразу включил обновлённую версию pip (поновее, чем та, которая в комплекте с 3.10.6) - чтобы он не ругался при первом запуске webui:
  - `python.exe -m ensurepip --upgrade`
  - `python.exe -m pip install -U pip`

С этим всем - у меня питонская часть ужалась до 11 Мб (sfx-exe - 13Мб). Таким макаром можно весь архив сократить до одного файла.
Вот инсталл с перечисленными изменениями: https://anonymfile.com/2qn81/python-310-6-portable.7z

Да, при весе моделей в гигабайты - 100Мб погоды не делают... но гитхаб беснуется, если репо достигает где-то гига. А - мало ли, сколько обновлённых версий будет.

**Comment by serpotapov** [comment]
Приветствую 🖐
Спасибо, буду изучать 🤝
