### ISSUE TITLE
How to run this on CPU?

### ISSUE THREAD

**Issue by Eselkopf** [serpotapov/stable-diffusion-portable#14]
I'm trying to run this on a windows laptop without a GPU. Is CPU supported?

**Comment by serpotapov** [comment]
Supported. You need to add arguments for launch Stable Diffusion without CUDA devices.
Arguments and other helpful info ➜ https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Command-Line-Arguments-and-Settings#:~:text=checkpoint%20in%20CI-,%2D%2Duse%2Dcpu,-%7Ball%2C%20sd%2C%20interrogate
