### ISSUE TITLE
нету файла webui-user.bat

### ISSUE THREAD

**Issue by lizratoff** [serpotapov/stable-diffusion-portable#15]
Здравствуйте

Распаковал,  установил с 3го раза, открылась. Второй раз не могу запустить, в папке нет файла webui-user.bat 
![image](https://user-images.githubusercontent.com/128276196/226155866-c4f32164-421b-461d-a9fc-f9bbf9cdf0d9.png)

**Comment by serpotapov** [comment]
Приветствую 🖐
![Screen-077](https://user-images.githubusercontent.com/24704153/226156007-0cdf3e2e-3d6c-4ba3-8581-a8408e4d0e34.png)

**Comment by lizratoff** [comment]
тупой

**Comment by lizratoff** [comment]
спасибо, прост чет не запускался

**Comment by serpotapov** [comment]
В следующий раз пиши в Discord ➜ https://discord.gg/xpuct
