### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by AlexRiman** [serpotapov/stable-diffusion-portable#16]
Good afternoon Thanks for the build, but there is a problem. After unpacking and running the bat, several folders and bat webui-user are created. We launch this batch file, the cmd window opens and immediately closes. Nothing happens, the interface does not start. What could be the problem? The antivirus generally demolished, unpacked the folder into the root directory of the disk.

**Comment by AlexRiman** [comment]
> Привет🖐 Вы запускаете файл от имени администратора? Не делай этого. Просто дважды щелкните файл webui-user.bat.

Нет, запускал просто двойным кликом. Так же заметил что не была создана папка models.

**Comment by AlexRiman** [comment]
![Снимок экрана 2023-03-21 163356](https://user-images.githubusercontent.com/128490203/226621987-554c79e9-3322-4485-9520-25013cb5954c.png)
ВОт что было создано bat файлом после распаковки

**Comment by AlexRiman** [comment]
Удалил все. Скачал сборку заново. Распаковал, запустил bat. Дождался установки. Все равно при запуске webui-user запускается командная строка и тут же закрывается. В чем может быть проблема?

**Comment by serpotapov** [comment]
Проблема с Вашим провайдером или файрволлом, потому что у Вас недокачиваются файлы.
Решите проблемы с сетью и попробуйте снова.

**Comment by AlexRiman** [comment]
Спасибо!
