### ISSUE TITLE
CPU Support?

### ISSUE THREAD

**Issue by Saltant** [serpotapov/stable-diffusion-portable#2]
On AMD i have error:
`RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'`

**Comment by XpucT** [comment]
> 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs

**Comment by Riyusaki** [comment]
Whether there is a way to use your solution on a Mac. I have an Imac Pro with an Intel Xeon processor.

**Comment by serpotapov** [comment]
On macOS you can use Diffusion Bee.
