### ISSUE TITLE
ERROR: No matching distribution found for torch==1.13.1+cu117

### ISSUE THREAD

**Issue by peter-hanzo** [serpotapov/stable-diffusion-portable#26]
I installed the portable version twice. today it stopped working for this reason:
ERROR: Cannot install basicsr==1.4.2, clean-fid==0.1.29, gradio==3.23.0 and transformers==4.25.1 because these package versions have conflicting dependencies.

I deleted all the files and tried to reinstall, but got this error:
ERROR: Could not find a version that satisfies the requirement torch==1.13.1+cu117 (from versions: none)
ERROR: No matching distribution found for torch==1.13.1+cu117
WARNING: There was an error checking the latest version of pip.

What are the solutions?

**Comment by serpotapov** [comment]
Just reinstall portable version. It will help.
