### ISSUE TITLE
RuntimeError: Error running command.

### ISSUE THREAD

**Issue by rozajeans444** [serpotapov/stable-diffusion-portable#29]
У меня нет опыта установки пайтон, гит и прочих сложных для меня программ, предназначение которых для меня не понятно, мне всего лишь нужно воспользоваться stable diffusion. 
Следуя инструкциям, у меня появилась какая-то ошибка. Когда я запускаю файл webui-user.bat, у меня в консоли вышло сообщение:
From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * branch              master     -> FETCH_HEAD
Already up to date.
venv "venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Traceback (most recent call last):
  File "C:\stable-diffusion-portable-main\launch.py", line 352, in <module>
    prepare_environment()
  File "C:\stable-diffusion-portable-main\launch.py", line 257, in prepare_environment
    run_python("import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'")
  File "C:\stable-diffusion-portable-main\launch.py", line 120, in run_python
    return run(f'"{python}" -c "{code}"', desc, errdesc)
  File "C:\stable-diffusion-portable-main\launch.py", line 96, in run
    raise RuntimeError(message)
RuntimeError: Error running command.
Command: "C:\stable-diffusion-portable-main\venv\Scripts\python.exe" -c "import torch; assert torch.cuda.is_available(), 'Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
Error code: 1
stdout: <empty>
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
AssertionError: Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check

Для продолжения нажмите любую клавишу . . .

В чем проблема? Что я опять сделал не так?

**Comment by rozajeans444** [comment]
Здравствуйте, как уже говорил, не разбираюсь в компьютерах и программировании. В тексте вверху, который я вставил из консоли, был фрагмент:
"Torch is not able to use GPU; add --skip-torch-cuda-test to COMMANDLINE_ARGS variable to disable this check'"
я добавил "--skip-torch-cuda-test" в файл "webui-user.bat" в надежде, что это поможет (я тогда еще не видел вашего ответа насчет видеокарты). 

По итогу в консоли вышло сообщение:
"From https://github.com/AUTOMATIC1111/stable-diffusion-webui
 * branch              master     -> FETCH_HEAD
Already up to date.
venv "venv\Scripts\Python.exe"
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 5ab7f213bec2f816f9c5644becb32eb72c8ffb89
Installing gfpgan
Installing clip
Installing open_clip
Installing xformers
Collecting xformers==0.0.17
  Downloading xformers-0.0.17-cp310-cp310-win_amd64.whl (112.6 MB)
     ---------------------------------------- 112.6/112.6 MB 150.0 kB/s eta 0:00:00
Installing collected packages: xformers
Successfully installed xformers-0.0.17

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: C:\stable-diffusion-portable-main\venv\Scripts\python.exe -m pip install --upgrade pip
Cloning Stable Diffusion into C:\stable-diffusion-portable-main\repositories\stable-diffusion-stability-ai...
Cloning Taming Transformers into C:\stable-diffusion-portable-main\repositories\taming-transformers...
Traceback (most recent call last):
  File "C:\stable-diffusion-portable-main\launch.py", line 352, in <module>
    prepare_environment()
  File "C:\stable-diffusion-portable-main\launch.py", line 286, in prepare_environment
    git_clone(taming_transformers_repo, repo_dir('taming-transformers'), "Taming Transformers", taming_transformers_commit_hash)
  File "C:\stable-diffusion-portable-main\launch.py", line 150, in git_clone
    run(f'"{git}" clone "{url}" "{dir}"', f"Cloning {name} into {dir}...", f"Couldn't clone {name}")
  File "C:\stable-diffusion-portable-main\launch.py", line 96, in run
    raise RuntimeError(message)
RuntimeError: Couldn't clone Taming Transformers.
Command: "git\cmd\git.exe" clone "https://github.com/CompVis/taming-transformers.git" "C:\stable-diffusion-portable-main\repositories\taming-transformers"
Error code: 128
stdout: <empty>
stderr: Cloning into 'C:\stable-diffusion-portable-main\repositories\taming-transformers'...
error: 7429 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output


Для продолжения нажмите любую клавишу . . ."

Здесь я уже ничего не понял и дальше ничего не делал.

Можно ли в моем случае прописать что-нибудь в файл "webui-user.bat", чтобы проблема была решена?
Мои характеристики ноутбука:

![ппп](https://github.com/serpotapov/stable-diffusion-portable/assets/133045783/3104e393-6fe3-4dc7-8716-91f7b775bf59)
вот, что смог найти по моему графическому процессору
![ппп2](https://github.com/serpotapov/stable-diffusion-portable/assets/133045783/0fae56c7-1df3-4777-ae9e-1c076f7fbd8c)

**Comment by rozajeans444** [comment]
можно ли установить данную сборку на мой ноутбук с видеопроцессором от AMD или нужна именно сборка для AMD?
Я пробовал EasyDiffusion, вроде как 1 кнопка и готово, но все равно ничего не вышло.
Это решается только установкой сборки для AMD, верно? Как описано здесь:
https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs
где нужно отдельно устанавливать Python 3.10.6  and git.
Я просто хочу понять, по какой инструкции мне следовать

**Comment by yagee** [comment]
> можно ли установить данную сборку на мой ноутбук с видеопроцессором от AMD или нужна именно сборка для AMD? Я пробовал EasyDiffusion, вроде как 1 кнопка и готово, но все равно ничего не вышло. Это решается только установкой сборки для AMD, верно? Как описано здесь: https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs где нужно отдельно устанавливать Python 3.10.6 and git. Я просто хочу понять, по какой инструкции мне следовать

@rozajeans444 

Я думаю имеет смысл попробовать сделать по этой [инструкции](https://github.com/AUTOMATIC1111/stable-diffusion-webui/wiki/Install-and-Run-on-AMD-GPUs#windows) (именно Windows + AMD)

Посмотреть как именно нужно устанавливать AUTOMATIC1111 можно [этом видео](https://www.youtube.com/watch?v=3cvP7yJotUM), но с оглядкой на инструкцию выше.
