### ISSUE TITLE
spaces in prompts

### ISSUE THREAD

**Issue by ramzzza** [serpotapov/stable-diffusion-portable#3]
Почему не поддерживаются пробелы в промптах? При нажатии на пробел страница вниз рпокручивается

**Comment by serpotapov** [comment]
Приветствую 🖐
Что-то с фокусом в текстовом поле в Вашем браузере. 
Лучше перейти на Cent ➜ https://youtu.be/zlLcry2IfZc.

**Comment by ramzzza** [comment]
спасибо. проблема только в chrome, в firefox работает.
